# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: |
    echo ${{ variables.GOARCH }}
    echo ${{ variables.GOOS }}
    echo '##vso[task.setvariable variable=GOARCH]arm64'
    echo '##vso[task.setvariable variable=GOOS]linux'
    echo ${{ variables.GOARCH }}
    echo ${{ variables.GOOS }}
  displayName: "Setting Go build environment variables"

- task: Go@0
  inputs:
    command: 'get'
    arguments: '-u github.com/golang/protobuf/{proto,protoc-gen-go}'
    workingDirectory: '$(System.DefaultWorkingDirectory)'
  inputs:
    command: 'get'
    arguments: '-u google.golang.org/grpc'
    workingDirectory: '$(System.DefaultWorkingDirectory)'
  inputs:
    command: 'get'
    arguments: 'github.com/boltdb/bolt/...'
    workingDirectory: '$(System.DefaultWorkingDirectory)'
  inputs:
    command: 'get'
    arguments: '-u github.com/gin-gonic/gin'
    workingDirectory: '$(System.DefaultWorkingDirectory)'
  inputs:
    command: 'get'
    arguments: 'gopkg.in/ini.v1'
    workingDirectory: '$(System.DefaultWorkingDirectory)'
  inputs:
    command: 'build'
    arguments: '-o bine_arm'
