FROM ubuntu:latest

WORKDIR /usr/bine/
COPY device_sdk ./device_sdk
# Any new pip3 requirements can be added here
# CMD pip3 install example
COPY bine ./
COPY hub_config.ini ./

RUN apt update

RUN apt install python3-pip -y

RUN apt-get install python3-uamqp -y

RUN pip3 install -r device_sdk/requirements.txt

RUN pip3 install --upgrade setuptools
 
EXPOSE 5000

CMD ["/bin/bash"]
