// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.14.0
// source: DownstreamCommands/CommandService.proto

package DownstreamCommands

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// The request message containing the user's name.
type CommandServiceRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CommandName string `protobuf:"bytes,1,opt,name=CommandName,proto3" json:"CommandName,omitempty"`
	Payload     string `protobuf:"bytes,2,opt,name=Payload,proto3" json:"Payload,omitempty"`
}

func (x *CommandServiceRequest) Reset() {
	*x = CommandServiceRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_DownstreamCommands_CommandService_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CommandServiceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandServiceRequest) ProtoMessage() {}

func (x *CommandServiceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_DownstreamCommands_CommandService_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandServiceRequest.ProtoReflect.Descriptor instead.
func (*CommandServiceRequest) Descriptor() ([]byte, []int) {
	return file_DownstreamCommands_CommandService_proto_rawDescGZIP(), []int{0}
}

func (x *CommandServiceRequest) GetCommandName() string {
	if x != nil {
		return x.CommandName
	}
	return ""
}

func (x *CommandServiceRequest) GetPayload() string {
	if x != nil {
		return x.Payload
	}
	return ""
}

// The response message containing the greetings.
type CommandServiceResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code    int32  `protobuf:"varint,1,opt,name=Code,proto3" json:"Code,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=Message,proto3" json:"Message,omitempty"`
}

func (x *CommandServiceResponse) Reset() {
	*x = CommandServiceResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_DownstreamCommands_CommandService_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CommandServiceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandServiceResponse) ProtoMessage() {}

func (x *CommandServiceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_DownstreamCommands_CommandService_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandServiceResponse.ProtoReflect.Descriptor instead.
func (*CommandServiceResponse) Descriptor() ([]byte, []int) {
	return file_DownstreamCommands_CommandService_proto_rawDescGZIP(), []int{1}
}

func (x *CommandServiceResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *CommandServiceResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_DownstreamCommands_CommandService_proto protoreflect.FileDescriptor

var file_DownstreamCommands_CommandService_proto_rawDesc = []byte{
	0x0a, 0x27, 0x44, 0x6f, 0x77, 0x6e, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x43, 0x6f, 0x6d, 0x6d,
	0x61, 0x6e, 0x64, 0x73, 0x2f, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x13, 0x68, 0x75, 0x62, 0x65, 0x64,
	0x67, 0x65, 0x70, 0x72, 0x6f, 0x78, 0x79, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x22, 0x53,
	0x0a, 0x15, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x20, 0x0a, 0x0b, 0x43, 0x6f, 0x6d, 0x6d, 0x61,
	0x6e, 0x64, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x43, 0x6f,
	0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x50, 0x61, 0x79,
	0x6c, 0x6f, 0x61, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x50, 0x61, 0x79, 0x6c,
	0x6f, 0x61, 0x64, 0x22, 0x46, 0x0a, 0x16, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x53, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a,
	0x04, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x43, 0x6f, 0x64,
	0x65, 0x12, 0x18, 0x0a, 0x07, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x32, 0x74, 0x0a, 0x07, 0x43,
	0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x12, 0x69, 0x0a, 0x0e, 0x52, 0x65, 0x63, 0x65, 0x69, 0x76,
	0x65, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x12, 0x2a, 0x2e, 0x68, 0x75, 0x62, 0x65, 0x64,
	0x67, 0x65, 0x70, 0x72, 0x6f, 0x78, 0x79, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x2e, 0x43,
	0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x2b, 0x2e, 0x68, 0x75, 0x62, 0x65, 0x64, 0x67, 0x65, 0x70, 0x72,
	0x6f, 0x78, 0x79, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x61,
	0x6e, 0x64, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x42, 0x16, 0x5a, 0x14, 0x2e, 0x2f, 0x44, 0x6f, 0x77, 0x6e, 0x73, 0x74, 0x72, 0x65, 0x61,
	0x6d, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_DownstreamCommands_CommandService_proto_rawDescOnce sync.Once
	file_DownstreamCommands_CommandService_proto_rawDescData = file_DownstreamCommands_CommandService_proto_rawDesc
)

func file_DownstreamCommands_CommandService_proto_rawDescGZIP() []byte {
	file_DownstreamCommands_CommandService_proto_rawDescOnce.Do(func() {
		file_DownstreamCommands_CommandService_proto_rawDescData = protoimpl.X.CompressGZIP(file_DownstreamCommands_CommandService_proto_rawDescData)
	})
	return file_DownstreamCommands_CommandService_proto_rawDescData
}

var file_DownstreamCommands_CommandService_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_DownstreamCommands_CommandService_proto_goTypes = []interface{}{
	(*CommandServiceRequest)(nil),  // 0: hubedgeproxycommand.CommandServiceRequest
	(*CommandServiceResponse)(nil), // 1: hubedgeproxycommand.CommandServiceResponse
}
var file_DownstreamCommands_CommandService_proto_depIdxs = []int32{
	0, // 0: hubedgeproxycommand.Command.ReceiveCommand:input_type -> hubedgeproxycommand.CommandServiceRequest
	1, // 1: hubedgeproxycommand.Command.ReceiveCommand:output_type -> hubedgeproxycommand.CommandServiceResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_DownstreamCommands_CommandService_proto_init() }
func file_DownstreamCommands_CommandService_proto_init() {
	if File_DownstreamCommands_CommandService_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_DownstreamCommands_CommandService_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CommandServiceRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_DownstreamCommands_CommandService_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CommandServiceResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_DownstreamCommands_CommandService_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_DownstreamCommands_CommandService_proto_goTypes,
		DependencyIndexes: file_DownstreamCommands_CommandService_proto_depIdxs,
		MessageInfos:      file_DownstreamCommands_CommandService_proto_msgTypes,
	}.Build()
	File_DownstreamCommands_CommandService_proto = out.File
	file_DownstreamCommands_CommandService_proto_rawDesc = nil
	file_DownstreamCommands_CommandService_proto_goTypes = nil
	file_DownstreamCommands_CommandService_proto_depIdxs = nil
}
