FROM binelogin.azurecr.io/hub_base_arm:latest
 
WORKDIR /usr/bine/
COPY device_sdk ./device_sdk

## Adding depnedencies
RUN pip3 install -r device_sdk/requirements.txt

RUN rm -rf ~/.cache/

COPY bine_arm ./
COPY *.ini ./
COPY start.sh ./
EXPOSE 5000

CMD ["./start.sh"]
