FROM binelogin.azurecr.io/hub_base_x86:latest
 
WORKDIR /usr/bine/
COPY device_sdk ./device_sdk
# Any new pip3 requirements can be added here
# CMD pip3 install example
COPY bine ./
COPY hub_config.ini ./
COPY alive.sh ./
EXPOSE 5000

CMD ["./alive.sh"]