FROM binelogin.azurecr.io/hub_base_x86:latest
 
WORKDIR /usr/bine/
COPY device_sdk ./device_sdk

## Adding depnedencies
RUN pip3 install -r device_sdk/requirements.txt

RUN rm -rf ~/.cache/

COPY bine ./
COPY *.ini ./
COPY alive.sh ./
COPY start_hub.sh ./
EXPOSE 5000

CMD ["./alive.sh"]