FROM binelogin.azurecr.io/hub_base_arm:latest
 
WORKDIR /usr/bine/
COPY device_sdk ./device_sdk
# Any new pip3 requirements can be added here
RUN pip3 install -r device_sdk/requirements.txt
COPY bine_arm ./
COPY *.ini ./
COPY start.sh ./
EXPOSE 5000

CMD ["./start.sh"]
