// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package goUpstreamTelemetry

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion7

// TelemetryClient is the client API for Telemetry service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TelemetryClient interface {
	// Sends TelemetryData to IOT Edge
	SendTelemetry(ctx context.Context, in *TelemetryRequest, opts ...grpc.CallOption) (*TelemetryResponse, error)
	// Sends TelemetryBatch Data to IOT Edge
	SendTelemetryBatch(ctx context.Context, in *TelemetryBatchRequest, opts ...grpc.CallOption) (*TelemetryResponse, error)
}

type telemetryClient struct {
	cc grpc.ClientConnInterface
}

func NewTelemetryClient(cc grpc.ClientConnInterface) TelemetryClient {
	return &telemetryClient{cc}
}

func (c *telemetryClient) SendTelemetry(ctx context.Context, in *TelemetryRequest, opts ...grpc.CallOption) (*TelemetryResponse, error) {
	out := new(TelemetryResponse)
	err := c.cc.Invoke(ctx, "/hubedgeproxytelemetry.Telemetry/SendTelemetry", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *telemetryClient) SendTelemetryBatch(ctx context.Context, in *TelemetryBatchRequest, opts ...grpc.CallOption) (*TelemetryResponse, error) {
	out := new(TelemetryResponse)
	err := c.cc.Invoke(ctx, "/hubedgeproxytelemetry.Telemetry/SendTelemetryBatch", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TelemetryServer is the server API for Telemetry service.
// All implementations must embed UnimplementedTelemetryServer
// for forward compatibility
type TelemetryServer interface {
	// Sends TelemetryData to IOT Edge
	SendTelemetry(context.Context, *TelemetryRequest) (*TelemetryResponse, error)
	// Sends TelemetryBatch Data to IOT Edge
	SendTelemetryBatch(context.Context, *TelemetryBatchRequest) (*TelemetryResponse, error)
	mustEmbedUnimplementedTelemetryServer()
}

// UnimplementedTelemetryServer must be embedded to have forward compatible implementations.
type UnimplementedTelemetryServer struct {
}

func (UnimplementedTelemetryServer) SendTelemetry(context.Context, *TelemetryRequest) (*TelemetryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendTelemetry not implemented")
}
func (UnimplementedTelemetryServer) SendTelemetryBatch(context.Context, *TelemetryBatchRequest) (*TelemetryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendTelemetryBatch not implemented")
}
func (UnimplementedTelemetryServer) mustEmbedUnimplementedTelemetryServer() {}

// UnsafeTelemetryServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TelemetryServer will
// result in compilation errors.
type UnsafeTelemetryServer interface {
	mustEmbedUnimplementedTelemetryServer()
}

func RegisterTelemetryServer(s grpc.ServiceRegistrar, srv TelemetryServer) {
	s.RegisterService(&Telemetry_ServiceDesc, srv)
}

func _Telemetry_SendTelemetry_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TelemetryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TelemetryServer).SendTelemetry(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/hubedgeproxytelemetry.Telemetry/SendTelemetry",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TelemetryServer).SendTelemetry(ctx, req.(*TelemetryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Telemetry_SendTelemetryBatch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TelemetryBatchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TelemetryServer).SendTelemetryBatch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/hubedgeproxytelemetry.Telemetry/SendTelemetryBatch",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TelemetryServer).SendTelemetryBatch(ctx, req.(*TelemetryBatchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Telemetry_ServiceDesc is the grpc.ServiceDesc for Telemetry service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Telemetry_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "hubedgeproxytelemetry.Telemetry",
	HandlerType: (*TelemetryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendTelemetry",
			Handler:    _Telemetry_SendTelemetry_Handler,
		},
		{
			MethodName: "SendTelemetryBatch",
			Handler:    _Telemetry_SendTelemetryBatch_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "goUpstreamTelemetry/TelemetryService.proto",
}
