# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import logger_pb2 as logger__pb2


class LogStub(object):
    """Interface exported by the server. Used for sending code logs as well as telemetry
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SendSingleLog = channel.unary_unary(
                '/pblogger.Log/SendSingleLog',
                request_serializer=logger__pb2.SingleLog.SerializeToString,
                response_deserializer=logger__pb2.Empty.FromString,
                )


class LogServicer(object):
    """Interface exported by the server. Used for sending code logs as well as telemetry
    """

    def SendSingleLog(self, request, context):
        """Accept a stream of SingleLog and send a dummy message
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_LogServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SendSingleLog': grpc.unary_unary_rpc_method_handler(
                    servicer.SendSingleLog,
                    request_deserializer=logger__pb2.SingleLog.FromString,
                    response_serializer=logger__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'pblogger.Log', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Log(object):
    """Interface exported by the server. Used for sending code logs as well as telemetry
    """

    @staticmethod
    def SendSingleLog(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/pblogger.Log/SendSingleLog',
            logger__pb2.SingleLog.SerializeToString,
            logger__pb2.Empty.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)
